# Generated by Django 5.1.1 on 2024-09-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_mobile"),
        ("content", "0003_alter_postitem_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perm",
            options={"ordering": ["name"], "verbose_name": "permission", "verbose_name_plural": "permissions"},
        ),
        migrations.AddField(
            model_name="perm",
            name="lang",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="content.language"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(blank=True, to="account.role"),
        ),
        migrations.AlterModelTable(
            name="roleperm",
            table=None,
        ),
    ]
