# Generated by Django 5.1.1 on 2024-09-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_perm_table_alter_role_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perm",
            options={"ordering": ["name"], "verbose_name": "Permission", "verbose_name_plural": "Permissions"},
        ),
    ]
