# Generated by Django 5.1.1 on 2024-09-14 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_perm_options"),
        ("content", "0005_alter_categoryitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="perm",
            name="lang",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="language_perms",
                to="content.language",
                verbose_name="language",
            ),
        ),
    ]
