# Generated by Django 5.1.1 on 2024-09-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_perm_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                related_name="users_roleperms", to="account.roleperm", verbose_name="roleperms"
            ),
        ),
    ]
