# Generated by Django 5.1.1 on 2024-09-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_user_roles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="roles",
            new_name="role_perms",
        ),
    ]
