# Generated by Django 5.1.1 on 2024-09-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="user",
        ),
        migrations.RemoveField(
            model_name="postitem",
            name="user",
        ),
    ]
