# Generated by Django 5.1.1 on 2024-09-15 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postitem",
            name="user",
        ),
    ]
