# Generated by Django 5.1.1 on 2024-09-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_remove_category_user_remove_postitem_user"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table="post",
        ),
    ]
