# Generated by Django 5.1.1 on 2024-09-17 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_remove_postitem_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postitem",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="content.post",
                verbose_name="post",
            ),
        ),
    ]
