# Generated by Django 5.1.1 on 2024-09-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_post_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="language",
            options={"verbose_name": "language", "verbose_name_plural": "languages"},
        ),
    ]
