# Generated by Django 5.1.1 on 2024-09-13 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_language_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="content.category", verbose_name="category"
            ),
        ),
    ]
